### ISSUE TITLE
Code in will not build under Linux (patch provided)

### ISSUE THREAD

**Issue by dominig** [cowelld/tackandlay_pi#10]
The latest code is currently provided by xxx does not compiled under Linux due to mixup of lowercase/uppercase in file names.

I provide a patch on my fork which fix the issue.
git@github.com:dominig/tackandlay_pi.git

**Comment by rgleason** [comment]
Sorry, I thought Dave was developing on Linux.

**Comment by dominig** [comment]
Re opening as yet not included in master.
(only sit on my fork)

**Comment by dominig** [comment]
PR done today #19

**Comment by dominig** [comment]
Closing following integration of #19 in master
