### ISSUE TITLE
Loading a polar crashes the plugin.

### ISSUE THREAD

**Issue by dominig** [cowelld/tackandlay_pi#11]
I have a polar for my boat which my not be perfect but is generally accepted by SW.
The tackandlay plugin crashes when it read that file (joined to the bug).

[Oceanis31-Finot-conq.pol.txt](https://github.com/cowelld/tackandlay_pi/files/182036/Oceanis31-Finot-conq.pol.txt)

**Comment by cowelld** [comment]
You'll have to give me some time. I haven't worked on that program in quite 
a while. I've downloaded your Polar and will look to see if I can find any 
problem but it looks pretty good.

Hasta,
Dave
----- Original Message -----

**Comment by rgleason** [comment]
COMMENTS about TACKANDLAY acceptance of TAB and SemiColon delimited Polars.

See the attached File

[Comment-on-TackandLay-TAB-SemiColon.txt](https://github.com/cowelld/tackandlay_pi/files/182779/Comment-on-TackandLay-TAB-SemiColon.txt)

**Comment by rgleason** [comment]
Well polars come in more than several flavors I find.  There is also a [space] delimited polar. That is another flavor that must be injested.  Also they have variable wind scales and wind increments, and variable degrees increments, they all should start at 0 and get to 180, but the increment variability must be accommodated.  I might suggest that Polar_pi has done some good work in this regard and it might be worthwhile looking at that for a good solution.

**Comment by rgleason** [comment]
By the way, using Notebook++ I was able to find and replace using
https://gist.github.com/ramons03/6152802   - see his way
 Notepad++AdvancedSearch.txt
Open the find/replace dialog.
At the bottom will be some Search mode options.  Select "Extended (\n \r \t \0 \x...)"
In either the Find what or the Replace with field entries, you can use the following escapes:
\n  new line (LF)
\r   carriage return (CR)
\t   tab character
\0  null character
\xddd   special character with code ddd
Notepad++RegularExpressions.txt

**Comment by rgleason** [comment]
So to change the first file below from [space] delimited to [tab] delimited I used notebook++ find&replace
with extended  button on, with a find [space]  and  replace /t .

The last file is the one that works in TackandLay right now. Take the text off both files.

[oceanis31-finot-conq-fix-angle-line-all-zero.csv.txt](https://github.com/cowelld/tackandlay_pi/files/182868/oceanis31-finot-conq-fix-angle-line-all-zero.csv.txt)

[oceanis31-finot-conq-fix-angle-line-all-zero-csv-space-to-TAB.pol.txt](https://github.com/cowelld/tackandlay_pi/files/182869/oceanis31-finot-conq-fix-angle-line-all-zero-csv-space-to-TAB.pol.txt)

I think tackandlay should accept [space] delimited, [tab] delimited, [;] delimited files with CRLF or LF at the end of line.
Also various Wind ranges 0-60 with different increments 2, 5, 10, 15 etc
Also degrees from 0 to 180 with different increments 2, 5, 10, 15 etc.
Also allowing 0 or 0.00 or 0.0 or "nothing" provided there is a delimiter.
If there are degree lines that are missing (0 degrees through 30 degrees for example) they are assumed to be all zeros and filled in, so the file is accepted.

**Comment by rgleason** [comment]
After I got dominig's polar working with TackandLay, [using Version 4.0 of Opencpn and the version of tackandlay from that time.  I was able to from Settings > Plugins  Enable TnL and then pick Preferences and "set" the Polar file to the Oceanis polar.   Then I was able to close settings, download a grib, Right click and pick move boat to here, then right click on a location with a tight reach and pick "Set Race Mark" the TnL selection.  From here I did not see what should probably happen.  When I click on the TnL icon, there is a message that pops up and says TnL is using the correct Oceanis polar....  oh oh , now it is says TnL cannot load this file.  Something is still wrong, even though the polar shows properly under Settings > Plugins.

**Comment by rgleason** [comment]
I will continue this on the Cruisers thread for TnL with screenshots.

**Comment by rgleason** [comment]
Here is a zip file with various formats for the polars.  These can all be read by Polar_pi.
[Oceanis31-finot-conq-Polar.zip](https://github.com/cowelld/tackandlay_pi/files/183018/Oceanis31-finot-conq-Polar.zip)

I could also give you some polars with different wind ranges and increments, etc. for testing.
[Sample-Polars-to-test.zip](https://github.com/cowelld/tackandlay_pi/files/183026/Sample-Polars-to-test.zip)

**Comment by rgleason** [comment]
I also think the plugin should allow  other types of Polar files to be loaded such as
.CSV,   .TXT,  in addition to .POL   Perhaps it should have an "All" selection dropdown for file endings too?

**Comment by rgleason** [comment]
When it has been given a polar file to ingest, it should resolve the variations and try the file, if the file does not work, leave a reasonably informative message on screen, and then simple not crash or freeze, but perhaps close with the message.

**Comment by rgleason** [comment]
Dominig
Please read the last 3 to 4 posts on this thread, it might help, even if it is not for Linux.
http://www.cruisersforum.com/forums/f134/tack-and-laylines-plugin-beta-138487.html

**Comment by dominig** [comment]
Ideally the code to read a Polar should be shared.
Finding a solution to work around the issue by playing with Tab and lowercase is not really acceptable compared to the general quality of OpenCPN code.

Sorry, I will not include a plugin in OpenSUSE distro which does require that type of workaround.

Importing the code from Weather Routing should be the first step, the second to make sure that the plugin never crashes. It could reject a file with an error message when formatting limits are reached but that's all.

**Comment by rgleason** [comment]
Agreed.  It should not be included.  Sorry. I thought it was working in Linux.

**Comment by dominig** [comment]
I have imported the polar file load code from polar_pi (both are GPLv2).
If you take my branch is does not crash anymore.
https://github.com/dominig/tackandlay_pi/commit/2cccf94ac1cff8dacd75b41961d9a11ebeb9cfba
Once that you have integrated my branch and tested you can close this bug.

(note I am raising an new bug on the UI, issue with OK button an dual display of Polar)

**Comment by rgleason** [comment]
Dominig, thank you! 
Will try it this morning.
