### ISSUE TITLE
After more than one use, pressing Cancel on Polar file section will display a new Polar File.

### ISSUE THREAD

**Issue by dominig** [cowelld/tackandlay_pi#14]
Load an initial Polar file from Tackandlay plugin Preference menu.
OK in the file load, the Plugin Configuration window is now in focus and a Polar Window is displayed.

Press a second time on the Tackandlay plugin Preference button.
independently of pressing OK, Cancel, Selecting a file or not, a new Polar Windows will be open each time.
As the new Window overlap exactly the previous one, it is not obvious, but moving the windows is possible and shows the bug.

Debug shows that when pressing Cancel the Polar load, display and refreshed are called in the same manner.

11:58:09 CET:     tackandlay_pi has loaded: /home/dominig/CartesOpenCPN/Polar/Oceanis31-Finot-conq2.pol
11:58:09 CET: tackandlay_pi exit show polar
11:58:09 CET: tackandlay_pi exit refresh polar
11:58:22 CET:     tackandlay_pi has loaded:     ?? pressing Cancel should not try to load any file??
11:58:22 CET: tackandlay_pi exit show polar    ?? Display works because old file data presence ??
11:58:22 CET: tackandlay_pi exit refresh polar
11:58:26 CET: Error: Failed to get the working directory (error 2: No such file or directory)
11:58:30 CET:     tackandlay_pi has loaded: /home/dominig/CartesOpenCPN/Polar/Oceanis31-Finot-conq2.pol
11:58:30 CET: tackandlay_pi exit show polar
11:58:30 CET: tackandlay_pi exit refresh polar

![tackandlay-20160323-1225](https://cloud.githubusercontent.com/assets/1193120/13983318/408b27b8-f0ef-11e5-8350-8ac14b27f39d.jpg)

**Comment by rgleason** [comment]
Dominig,
I git cloned your branch, mkdir build directory and put current opencpn.lib in it.
Then copied the normal buildwin files for v 4.2 into buildwin  (don't know if this is needed)
Then  at MS command prompt 
cmake -T v120_xp ..

And there is an note about a file missing...


> 

C:\Users\Frederick\Documents\GitHub\o-plugin\dom-tackandlay_pi\build>cmake -T v120_xp ..
-- Building for: Visual Studio 12 2013
-- *** Staging to build tackandlay_pi ***
-- Found wxWidgets: debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxbase30ud.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxbase30u.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxmsw30ud_core.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxmsw30u_core.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxbase30ud_net.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxbase30u_net.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxbase30ud_xml.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxbase30u_xml.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxmsw30ud_html.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxmsw30u_html.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxmsw30ud_adv.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxmsw30u_adv.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxpngd.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxpng.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxtiffd.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxtiff.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxjpegd.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxjpeg.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxzlibd.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxzlib.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxregexud.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxregexu.lib;debug;C:/wxWidgets-3.0.2/lib/vc_dll/wxexpatd.lib;optimized;C:/wxWidgets-3.0.2/lib/vc_dll/wxexpat.lib;winmm;comctl32;rpcrt4;wsock32 (found version "3.0.2")
-- Found OpenGL: opengl32
-- Found OpenGL...
--     Lib: glu32opengl32
--     Include:
-- Found Gettext: C:/Program Files (x86)/Poedit/GettextTools/bin/msgmerge.exe
-- Install Prefix: C:/Program Files (x86)/tackandlay_pi
-- Configuring done
CMake Error at CMakeLists.txt:96 (ADD_LIBRARY):
  Cannot find source file:

    src/nmea0183/latlong.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: tackandlay_pi
-- Generating done
-- Build files have been written to: C:/Users/Frederick/Documents/GitHub/o-plugin/dom-tackandlay_pi/build

>

**Comment by rgleason** [comment]
Copied latlong.hpp from David's git 
Then cmake -T v120_xp ..
and it asks for 
    src/nmea0183/response.hpp

**Comment by rgleason** [comment]
I don't find  src/nmea0183/response.hpp
in Davids git

Now I am stuck

**Comment by dominig** [comment]
I do not know how you cloned my fork but it does provide latlong.cpp
To be honest, I have not changed anything in those files, except some capitalisation, as Linux by opposition to Windows differentiate lower and uppercase in file-names.

Let restart by the base, to get my branch
  git@github.com:dominig/tackandlay_pi.git
it will create a file stucture where you will find latlong.cpp here.
>  ll tackandlay_pi/src/nmea0183/latlong.cpp 
   -rw-r--r-- 1 dominig users 2941 23 mars  15:09 tackandlay_pi/src/nmea0183/latlong.cpp

All the source files are either in src or src/nmea0183
If they are not there, something went wrong during the clone.
Scan the directory and you should find the files.

Also check that you have the correct  pre-requisit for a Windows build
  http://opencpn.org/ocpn/compiling_source_windows

Get a look at the files:
    build/CMakeFiles/CMakeOutput.log
    build/CMakeFiles/tackandlay_pi.dir/CXX.includecache
They normally are  full of info

"Then copied the normal buildwin files for v 4.2 into buildwin (don't know if this is needed)"
I do not know if that phase is required or even problem free. It's not listed in the documentation page.
But as I have no Windows to try ....

Dominig

**Comment by rgleason** [comment]
Dominig,  I am going to remove the local git and clone again, it must be a glitch of some sort. I am excited about this.

**Comment by rgleason** [comment]
Dominig, The above was a excellent help. Thankyou.  After trying a number of things  basically git cloning that did not succeed at bringing down all the files I needed, I made a zip of your repository and expanded it. This got me most of the way there, past two main errors,
[TackandLay-build-prolem.txt](https://github.com/cowelld/tackandlay_pi/files/187053/TackandLay-build-prolem.txt)
 except I was still missing some files so I just copied them from Dave's local repository, which is possibly why I am still having trouble, because you might have changed one or two of them.   The 25 errors are toward the bottom of the attached file.
Could you take a look an advise if one of these files might be different than Dave's?

Finally tried zipping your fork and unpacking it.
That took care of the first two errors.  
Then I had to add these files from Dave Coweeld's git
latlong.hpp
satinfo.h
sentence.cpp
sentence.hpp
RMC.hpp
RMB.hpp
response.hpp

This has never happened to me before. Trouble with git clone? 
Our internet connection must be having trouble or something.
Thanks!
 
[TackandLay-build-prolem.txt](https://github.com/cowelld/tackandlay_pi/files/187054/TackandLay-build-prolem.txt)

**Comment by dominig** [comment]
Rick;

as your issue have nothing in relation with the bug, but rather with your build environment, let process that directly in 1:1

Just contact me at my email.
dominig dot arfoll at fridu.net

Regards

Dominig
