### ISSUE TITLE
Need a file called 'ocpndc.h' to compile

### ISSUE THREAD

**Issue by rgleason** [cowelld/tackandlay_pi#3]
Tried again after git fetch and git pull with new files downloaded.
Same problem.  Do I have this file available with Opencpn src?

```
Build FAILED.

"C:\Data-Dart\Up-Soft\Navigation\o-plugin\tackandlay_pi\build\ALL_BUILD.vcxproj"
 (default target) (1) ->
"C:\Data-Dart\Up-Soft\Navigation\o-plugin\tackandlay_pi\build\tackandlay_pi.vcxp
roj" (default target) (3) ->
(ClCompile target) ->
  c:\data-dart\up-soft\navigation\o-plugin\tackandlay_pi\src\tackandlay_pi.h(34)
: fatal error C1083: Cannot open include file: 'ocpndc.h': No such file or direc
tory [C:\Data-Dart\Up-Soft\Navigation\o-plugin\tackandlay_pi\build\tackandlay_pi
.vcxproj]

    0 Warning(s)
    1 Error(s)
```

**Comment by cowelld** [comment]
Although "ocpndc.h" is referenced in several OpenCPN modules it isn't really 
needed in the reference list for this program. I deleted it and the plug-in 
compiled fine.
My compiler doesn't show a reference for the header file so I don't really 
know where it is or isn't. Maybe it's virtual.


----- Original Message -----

**Comment by rgleason** [comment]
For Windows complle
In the file tackandlay_pi.h  Line 34 change with "//"
#include "wx/wx.h"
#include <wx/glcanvas.h>
// #include "ocpndc.h"

Then copy opencpn.lib for version 4.0 to the /build directory
and it will then complie from the /build directory with

cmake ..
cmake --build .
cmake --build . --config release
cpack
leaving an executable

**Comment by rgleason** [comment]
Actually you do not need the file. You just need to comment out its inclusion in src/tackandlay_pi.h Line 34
