### ISSUE TITLE
Errors while compiling for OSX

### ISSUE THREAD

**Issue by ptulp** [cowelld/tackandlay_pi#7]
Dave,

I encountered the following error and 3 warnings when I compiled for OSX.
The error (number 1 below) could be solved by using labs i.s.o. abs.
The 3 warnings (numbers 2-4) looked to me as the actions should be comparisons i.s.o. settings.
Are you sure that this is intentional?

Regards,
Peter

1 tackandlay_pi/src/TackandLay_pi.cpp:681:20: error: call to 'abs' is ambiguous
    double speed = abs( SOG * cos(deg2rad(TWA)));

2 tackandlay_pi/src/TackandLay_pi.cpp:538:19: warning: using the result of an assignment as a condition without parentheses
      [-Wparentheses]
      if(Boat.HDG = 0)
         ~~~~~~~~~^~~
3 tackandlay_pi/src/TackandLay_pi.cpp:761:34: warning: using the result of an assignment as a condition without parentheses
      [-Wparentheses]
        for (j_wdir = 59; j_wdir = 30; j_wdir--) // 180 -> 90 deg TWA
                          ~~~~~~~^~~~

4 tackandlay_pi/src/TackandLay_pi.cpp:816:34: note: use '==' to turn this assignment into an equality comparison
        for (j_wdir = 59; j_wdir = 30; j_wdir--) // 180 -> 90 deg TWA
                                 ^
                                 ==

**Comment by rgleason** [comment]
Peter, thank you. I was going to run the debug version today. Yous saved me the trouble.
