### ISSUE TITLE
In Windows, when enable plugin, it eventually stalls

### ISSUE THREAD

**Issue by rgleason** [cowelld/tackandlay_pi#9]
In windows, when plugin is enabled, there is a browser window that opens and prompts for selection of the the polar file.  I browse to  plugin/weather_routing_pi/data/polars  and select a polar.
The polar shows properly in a window with OK".  Hit ok and the loading of the polar stops and O screen turns black and I have to shut O down.

When I Open O again, and click on the tack and lay icon, a message comes up
File currently loading is c:\progam files (x86)\ Opcon4.2.0\ plugins \ weatherrouting\ data\ C_C32.pol
"OK"   Everytiung seems ok

I then load a VDR file and I see a boat shape momentarily and then the screen turns black.

Can we get this going in Windows? Please?

**Comment by cowelld** [comment]
I haven't re-compiled the plugin with the later versions of OpenCPN and so 
don't have a feel for what it does.
There's been a great deal of changes made with the graphics. I may look at 
it this week depending on time available etc.

Hasta,
Dave

----- Original Message -----
